modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="camper" #mandatory
version="0.1" #mandatory
displayName="Camper" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="camper.png" #optional
credits="" #optional
authors="Itamar Denkberg" #optional
description='''
'''
[[dependencies.camper]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.camper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"